# id: (status, reason)
# KEEP = in-scope EVM contract-logic vuln on ETH/BSC/ARB/BASE reachable by an unprivileged attacker
# BORDER = kept but flagged
# DROP = out of scope
C={
1:('DROP','Cosmos/THORChain-fork app-chain state machine (Trade Account, pool math) — no EVM contract'),
2:('KEEP','BSC: FoxLpBondsPool.stake() prices LP bond off manipulable Pancake spot quote'),
3:('DROP','Layer-1 consensus/validator bug (empty-block minting) — not contract code'),
4:('KEEP','Ethereum: USM defund() split-invariance / rounding in FUM redemption curve'),
5:('DROP','Payment-processor wallet drain, cause undisclosed; no contract vuln identified'),
6:('DROP','Oraichain (Cosmos app-chain) native EVM module mint path — not a target chain'),
7:('DROP','XRPL/Coreum relayer deposit-verification logic — off-chain + non-target chain'),
8:('KEEP','Arbitrum: manager-signature replay across 21 UniV3 LP positions + spot-price valuation'),
9:('DROP','Weak RNG in CryptoJS dependency — supply-chain/key predictability'),
10:('KEEP','Ethereum: LaunchpadFactoryAuto.launch() forwards attacker calldata to V4 PositionManager'),
11:('DROP','Lightning/LSP infrastructure compromise'),
12:('KEEP','RWA strategy behind XLP vault, misconfiguration since deployment — contract-side, chain unconfirmed'),
13:('KEEP','BSC: LpdFi buy()/claimInterest() priced off thin Pancake LPD/USDC spot reserves'),
14:('KEEP','BSC: unprotected public claim() in MokeReleaseContract drains reserve pool'),
15:('DROP','Hardware-wallet firmware entropy bug'),
16:('KEEP','Ethereum: ExchangeIssuance TOCTOU on SetToken positionMultiplier via attacker manager hook'),
17:('BORDER','BSC: signer key hardcoded in ZhaiquanBuy leaked, but buy() has no discount floor/bounds check — on-chain contract defect, off-chain trigger'),
18:('KEEP','BSC: Pro token reward-on-transfer self-dealing, permissionless player/winner registration'),
19:('KEEP','BSC: LULA public claimReward()/recycle() redeems against attacker-deflated pool'),
20:('DROP','Contract owner privileges compromised (key) to mint WEMIX$'),
21:('DROP','Independent solver off-chain database compromised; HTLC contracts behaved correctly'),
22:('DROP','Unauthorized access to bridge operator credentials'),
23:('DROP','X account + wallet compromise'),
24:('KEEP','Ethereum: permissionless trackPurchase() sizes rewards from balance deltas, no payment check'),
25:('KEEP','Ethereum: permissionless registerNewBond + crafted payoff mispriced by bondPricer'),
26:('DROP','Hot-wallet compromise'),
27:('KEEP','Ethereum: Verus bridge import path mints unbacked payouts (repeat of the May flaw)'),
28:('DROP','Supra chain — not a target chain'),
29:('DROP','Compromised validator hot keys met the quorum'),
30:('KEEP','BSC: MakerDAO-fork Median Oracle/Spotter poke with no deviation or floor checks'),
31:('DROP','Solana perps'),
32:('DROP','Cardano-side lock address drained — not a target chain'),
33:('DROP','Solana liquidity pools'),
34:('DROP','Ledger app nonce-generation flaw leaking keys'),
35:('DROP','Solana event spoofing against off-chain relayer'),
36:('DROP','Solana lending'),
37:('DROP','Compromised oracle signer key; contract behaved as designed'),
38:('DROP','Bitcoin hot wallet outflow, undisclosed cause'),
39:('KEEP','Ethereum: abandoned BarnBridge governance captured, proxy re-pointed to sweep impl over live approvals'),
40:('BORDER','Arbitrum: mark-price manipulation in a thin pre-launch CLS market — economic/pricing design, on-chain'),
41:('KEEP','Ethereum: DaiDripsHub.give() unchecked uint128->int128 cast flips transfer direction'),
42:('KEEP','Arbitrum: Sodium ERC-4337 account grants approvals during UserOp validation; session-key validation bypass'),
43:('KEEP','Ethereum: Chi ArbitrageV5.burn() redeems at hardcoded $1 peg with no spot check (mint() has one)'),
44:('DROP','Hedera — not a target chain; third-party oracle feed'),
45:('KEEP','Ethereum: FleetCommander NAV = live sum of Ark totalAssets() with no manipulation guard'),
46:('DROP','Solana DAO governance — tokens bought, no contract bug'),
47:('KEEP','Ethereum: Hinkal prooflessDeposit()/transact() note-to-nullifier binding failure (double-spend)'),
48:('KEEP','Ethereum: Edel lending values wrapped xStock via mutable ERC4626 convertToAssets()'),
49:('KEEP','BSC: AIDCToken lets ordinary transfers burn accumulated sell amounts out of the AMM pair'),
50:('DROP','Frontend supply-chain script injection'),
51:('KEEP','Ethereum: Lixir vault-token permit accepts a dummy signature (only checks ecrecover != 0)'),
52:('DROP','Frontend/subdomain drainer injection'),
53:('DROP','Cardano wallet key-generation flaw'),
54:('DROP','Polygon — not a target chain'),
55:('DROP','Frontend/subdomain drainer injection'),
56:('DROP','Forged SGX attestation / prover registration — proof-system and infrastructure, not reachable contract logic'),
57:('DROP','Cosmos app-chain proof minting'),
58:('DROP','Off-chain MEV bot approval-generation logic; SlowMist explicitly states victim contracts were not vulnerable'),
59:('KEEP','BSC: OLPC _update() burns pair balance and desyncs reserves; owner had set an absurd decimalsValue 46d earlier'),
60:('DROP','Namada MASP/IBC — not a target chain'),
61:('DROP','Starknet — not a target chain (non-EVM)'),
62:('KEEP','BSC: JB helper uses live JB balance to sell/burn/sync through the JB/USDT pair'),
63:('KEEP','Ethereum: Aztec RollupProcessorV2 immutable escape hatch publishes an unconstrained proof_id'),
64:('KEEP','BSC: LBPHashrate._update() reachable via zero-value transferFrom, mints reward into the pair'),
65:('KEEP','BSC: DIP _transfer() missing return for router-routed trades causes double transfer'),
66:('KEEP','Ethereum: Thetanuts legacy index vault mint/claim redemption math with zeroed component transfers'),
67:('KEEP','Ethereum: Aztec Connect Decoder numRealTxs proven-vs-settled mismatch; processRollup permissionless'),
68:('DROP','Solana AMM program'),
69:('DROP','Secret Network CosmWasm contract — not a target chain'),
70:('DROP','Foundation member private keys compromised'),
71:('KEEP','DN404/BT404 shared-codebase ownership/underflow flaw in an Asterix fork of Flooring'),
72:('DROP','Sui Move contracts — not a target chain'),
73:('KEEP','Ethereum: NovaBox adds dual depositors to the dividend list without initialising checkpoints'),
74:('BORDER','Ethereum: Aragon DAO with 16,384 TOP supply and no timelock; mint proposal created+voted+executed in one tx'),
75:('DROP','Syscoin UTXO-side minting — not a target chain'),
76:('KEEP','Ethereum: Flooring V2 / BT404 packed-ownership alias + underflow mints near-infinite fpTokens'),
77:('KEEP','Ethereum: Ambient surplus-collateral accounting across HotProxy/WarmPath/ColdPath'),
78:('DROP','Server root compromise'),
79:('KEEP','BSC: DTXT forgeable add-liquidity detection bypasses sell fees'),
80:('KEEP','BSC: ATMToken._transfer() auto-dumps 20% of its own reserves at amountOutMin=0; per-address guards farmable'),
81:('KEEP','BSC: permissionless triggerAutoBurn() burns from the pair then sync()s reserves'),
82:('KEEP','BSC: ApeYieldVault.migrateToVotingEscrow accepts duplicate pool IDs, inflating the lock'),
83:('DROP','Gnosis Chain — not a target chain'),
84:('DROP','Social engineering / phishing DMs'),
85:('DROP','Core contract control obtained (key compromise) to mint TSR'),
86:('KEEP','Storage-slot collision between a rewards mapping and Solady ReentrancyGuard fixed slot in getReward()'),
87:('DROP','Off-chain Merkle proposer/approver keys compromised'),
88:('DROP','Cloud API endpoint vulnerability'),
89:('DROP','Contract key / signing authority compromised'),
90:('DROP','Bridge backend message forgery — off-chain'),
91:('KEEP','BSC: AROS token/pool logic drained via the AROS/USDT Pancake pair'),
92:('KEEP','BSC: cliamRewred() verify() accepts ecrecover==address(0) against a zeroed admin'),
93:('KEEP','BSC: YSDAO Staking.sync() has no access control; add/remove-liquidity detection is forgeable'),
94:('KEEP','BSC: removeLiquidityViaContract sends BNB before zeroing lpInfo — classic reentrancy'),
95:('BORDER','BSC: undisclosed owner-only DXLOCKERLP backdoor in an unverified locker, but the actor held ownership'),
96:('KEEP','onlyOwner check accepts owner == address(0), letting anyone re-own a renounced token'),
97:('DROP','Deployer EOA private key compromised'),
98:('DROP','Multisig transaction recipient tampering'),
99:('BORDER','BSC: SKP _runSpecialPairFlow redistributes unbounded treasury to a whitelisted address the owner set 6d prior — insider-engineered'),
100:('KEEP','Ethereum: WUSD._englove has no per-address claim ledger — Sybil-farmable uncapped subsidy'),
101:('KEEP','Ethereum+Base: Safe module trusts a caller-supplied sourceAddress string on the permissionless Axelar express path'),
102:('DROP','Issuer contract keys suspected compromised'),
103:('KEEP','Ethereum: SignatureChecker given an attacker-supplied signer source returns true'),
104:('DROP','Six-year-old operational wallet private key compromised (Polygon)'),
105:('KEEP','Arbitrum: USDF vault re-entrant deposit/withdraw against a fixed daily tokenPrice with share rounding'),
106:('KEEP','Ethereum: abi.encodePacked hash collision in OmniServiceProxy retry-message verification'),
107:('DROP','Tor P2P client message spoofing (Monero)'),
108:('DROP','Prompt-injection social engineering of an agent'),
109:('DROP','Algorand — not a target chain'),
110:('KEEP','Ethereum: Verus bridge import path (first exploitation of the flaw re-hit in July)'),
111:('DROP','Monad admin key leak; also not a target chain'),
112:('KEEP','Arbitrum: MetaSea RedeemPosition distributor drained via flash-loan-manipulated pricing'),
113:('DROP','GG20 TSS key-material leakage'),
114:('DROP','Bridge-minter EOA signed the fake wrapTo() calls — key compromise'),
115:('DROP','TRON — not a target chain'),
116:('KEEP','Arbitrum: Colony EtherRouter meta-transaction self-call defeats DSAuth'),
117:('KEEP','Arbitrum: EIP-2535 diamond with an initialize(address) selector whose _initialized slot stayed 0'),
118:('KEEP','BSC: hardcoded backdoor in the verified Staking contract, reached with an EIP-7702 type-4 tx'),
119:('DROP','Polygon — not a target chain'),
120:('DROP','Polygon — not a target chain'),
121:('DROP','TON side of the cross-chain layer'),
122:('DROP','X account compromise'),
123:('KEEP','Arbitrum: unprotected initializer on the V1 Dark Pool proxy after a desynced migration'),
124:('KEEP','Ethereum: permissionless registerAllowedOrderSigner + authorization keyed on taker instead of maker'),
125:('KEEP','Ethereum: IPayer.pay callback takes payer/token/amount from the lock payload without checking the lock initiator'),
126:('KEEP','Leveraged Lido module drained; mechanism not publicly detailed'),
127:('DROP','Bitcoin P2P trade protocol / modified clients'),
128:('DROP','AWS Spring Boot Actuator heap dump leaked the contract keys'),
129:('DROP','Upgrade key leaked, used to upgrade the bridge'),
130:('DROP','SWEAT is a NEAR-ecosystem token; drain and laundering ran through Ref Finance/Wormhole'),
131:('DROP','Sui Move perps'),
132:('KEEP','Ethereum: RWAVault overrides ERC4626 withdraw without the allowance spend when msg.sender != owner'),
133:('KEEP','BSC: JUDAO sell hook drains JUDAO from its own Pancake pair via sync/isBurnPair'),
134:('KEEP','Ethereum(+3): GatewayEVM.execute arbitrary-call sink with missing access control on GatewayZEVM.call'),
135:('KEEP','Base: oracle registered with a non-existent UniV3 fee tier 42, so getPool() returned address(0)'),
136:('DROP','Sui Move rewards contract'),
137:('DROP','HyperEVM/MegaETH (not target chains) and a compromised admin multisig'),
138:('KEEP','Ethereum: EIP-712 signature covers only keccak(SwapInfo.data), not aggregator/fromToken/toToken/amount'),
139:('KEEP','Base: router transfers a USDC-scaled quote as cbBTC units — decimal/asset mismatch'),
140:('DROP','Sui vaults'),
141:('KEEP','Ethereum: first-depositor share-rounding on a freshly deployed vault holding pre-existing WBTC'),
142:('KEEP','Ethereum: REVLoans.borrowFrom registers a caller-supplied loan source, forging accounting context'),
143:('DROP','Corporate SaaS breach'),
144:('DROP','Avalanche — not a target chain'),
145:('DROP','LayerZero DVN RPC node infrastructure compromise'),
146:('DROP','DNS registrar compromise'),
147:('DROP','NEAR — not a target chain'),
148:('DROP','Exchange hot-wallet breach'),
149:('KEEP','Ethereum: redeem() accepts duplicate NFT IDs and only advances nextRedeem after payout'),
150:('DROP','Frontend/domain compromise'),
151:('KEEP','Ethereum(+Base/BSC/Arb): MMR VerifyProof() does not enforce leaf_index < leafCount'),
152:('DROP','Dango app-chain insurance-fund logic'),
153:('BORDER','BSC: LisaVault referral tiers self-dealt via proxy contracts, but stage 1 was the deployer redeeming their own LP'),
154:('KEEP','Base: Settings.setContractAddress()/setBatchAddress() missing onlyOwner after a refactor'),
155:('DROP','AI-assisted social engineering of an employee device'),
156:('KEEP','BSC: AethirOFTAdapter ownership transfer reachable due to missing/bypassed onlyOwner'),
157:('BORDER','BSC(+multi): SquidMulticall.run() is permissionless by design; victim had approved it — design flaw, not a code bug'),
158:('KEEP','BSC: TGAI reserve manipulation via sync() on the Pancake V2 pair'),
159:('DROP','Linea — not a target chain'),
160:('KEEP','BSC: TMM burned to dead address to collapse the pair reserve to 1 TMM, then swapped out'),
}
